In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("spotify_millsongdata.csv")

In [3]:
df.head()

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [4]:
df

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...
...,...,...,...,...
57645,Ziggy Marley,Good Old Days,/z/ziggy+marley/good+old+days_10198588.html,Irie days come on play \r\nLet the angels fly...
57646,Ziggy Marley,Hand To Mouth,/z/ziggy+marley/hand+to+mouth_20531167.html,Power to the workers \r\nMore power \r\nPowe...
57647,Zwan,Come With Me,/z/zwan/come+with+me_20148981.html,all you need \r\nis something i'll believe \...
57648,Zwan,Desire,/z/zwan/desire_20148986.html,northern star \r\nam i frightened \r\nwhere ...
57649,Zwan,Heartsong,/z/zwan/heartsong_20148991.html,come in \r\nmake yourself at home \r\ni'm a ...

In [5]:
df.shape

(57650, 4)

In [6]:
df.isnull().sum()

artist    0
song      0
link      0
text      0
dtype: int64

In [7]:
df=df.sample(10000).drop("link",axis=1).reset_index(drop=True)

In [8]:
df

,artist,song,text
0,Miley Cyrus,Find Your Self In You,She never thought that she would \r\nGet her ...
1,Morrissey,Mexico,In Mexico \r\nI went for a walk to inhale \r...
2,Styx,Lorelei,"When I think of Lorelei, my head turns all aro..."
3,Maroon 5,Goodnight Goodnight,You left me hanging from a thread we once swun...
4,Nina Simone,Do What You Gotta Do,Jimmy Webb \r\n \r\nDo what you gotta do \r...
...,...,...,...
9995,Joni Mitchell,Come In From The Cold,Back in 1957 \r\nWe had to dance a foot apart...
9996,Tori Amos,Black Swan,"Ride on, ride on friends of the black swan \r..."
9997,Nat King Cole,Look Out For Love,Look out where you're going \r\nThere's dange...
9998,Blur,I Broadcast,I love the aspects of another city \r\nThe re...
9999,Christmas Songs,Christmas Time Is Here,Christmas time is here \r\nHappiness and chee...

In [9]:
df.text[0]

"She never thought that she would  \r\nGet her second chance  \r\nRunning so far from all she's ever known  \r\nConvinced she's lost all meaning  \r\nWhere did her dreams go  \r\nStill she knew that there was something more  \r\n  \r\nDon't be scared, there's someone there  \r\nTo say these words you need to hear  \r\n  \r\nChorus  \r\nDon't let anyone tell you that your not strong enough  \r\nDon't give up, there's nothing wrong with just being yourself  \r\nSo come on and raise your voice  \r\nAnd sing hey, heyyyahh  \r\n  \r\nYou'll find yourself in you  \r\n  \r\nSometimes people tell you  \r\nBe like me to fit in  \r\nDo you know your identity is not in them  \r\n  \r\nDon't be scared, there's someone there  \r\nTo say these words you need to hear  \r\n  \r\nChorus  \r\n  \r\nWhy should I measure the world  \r\nBy someone else's design  \r\nOh I won't let this fly by  \r\nHey look over here I just found the real me  \r\nNow it's your turn to see  \r\nNow it's your turn to see  \r\n  \r\nChorus\r\n\r\n"

In [10]:
df= df.sample(10000)

#TEXT PREPROCESSING

In [11]:
df.text=df.text.str.lower()

In [12]:
# df.text= df.text.replace('\r','',regex=True).replace('\n','',regex=True)

This is a regular expression (regex) pattern.

🔹 \s

Means any whitespace character, including:

space " "

newline \n

carriage return \r

tab \t

🔹 +

Means one or more

So:

\s+

means:

“One or more whitespace characters”

🔎 What does this line do?
.str.replace(r'\s+', ' ', regex=True)

It replaces:

multiple spaces, \n, \r, tabs

with

a single space
🔥 Example

Before:

Hello   world

This   is   text

After:

Hello world This is text

Clean and single-spaced.

🔎 Why r before the string?
r'\s+'

r means raw string.

Without r, Python may misinterpret \s as an escape character.

So always use:

r'\s+'

when writing regex.

🔎 Why regex=True?

Because we are using a regular expression pattern.

If regex=False, Pandas treats \s+ as normal text, not a pattern.

In [13]:
df.text=df.text.replace(r'\s+',' ',regex=True)

In [14]:
df.text=df['text'].str.strip()

In [15]:
df.text[1]

'in mexico i went for a walk to inhale the tranquil, cool, lover\'s air but i could taste a trace of american chemical waste and the small voice said "what can we do?" in mexico i went for a walk to inhale the tranquil, cool, lover\'s air but i could sense the hate from the lone star state and a small voice said "what can we do?" it seems if you\'re rich and you\'re white you\'ll be alright i just don\'t see why this should be so if you\'re rich and you\'re white you\'ll be alright i just don\'t see why this should be so in mexico i lay on the grass and i cried my heart out for want of my love oh, for want of my love oh, for want of my love it seems if you\'re rich and you\'re white you think you\'re so right i just don\'t see why this should be so if you\'re rich and you\'re white then you\'ll be ok i just don\'t see why this should be so in mexico i lay on the grass and i cried my heart out for want of my love for want of my love for want of my love for want of my love'

In [16]:
import nltk
from nltk.stem.porter import PorterStemmer

In [17]:
stemmer = PorterStemmer()

In [18]:
# it is from list comprehension
'''def token(txt):
    token = nltk.word_tokenize(txt)
    a =[stemmer.stem(w) for w in token]
    return " ".join(a)'''

'def token(txt):\n    token = nltk.word_tokenize(txt)\n    a =[stemmer.stem(w) for w in token]\n    return " ".join(a)'

In [19]:
def token(txt):
    token=nltk.word_tokenize(txt)
    a=[]
    for w in token:
        a.append(stemmer.stem(w))
    return" ".join(a)

In [20]:
token("u are beautifull,beauti")

'u are beautiful , beauti'

In [21]:
df['text'].apply(lambda x: token(x))

9489    up everi morn long befor day cook her breakfas...
4681    lover in the back seat boy in the back street ...
1173    we live in the land of plenti but mani thing a...
1774    oh babi , i 'll buy you a diamond ring oh babi...
9837    your father wa a rounder he play that rock and...
                              ...
9995    back in 1957 we had to danc a foot apart and t...
4593    la la , la la la la la na na na na na , la la ...
5331    [ vers 1 ] you got yourself some action said y...
5291    it 's rotten , so rotten here so rotten , ah ,...
7226    wake up here i go cram it all down my throat s...
Name: text, Length: 10000, dtype: object

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [23]:
tfid = TfidfVectorizer(analyzer ='word',stop_words='english')

In [24]:
X =tfid.fit_transform(df['text'])

In [29]:
similar=cosine_similarity(X)

In [41]:
def recommend(songs):
    idx= df[df['song']==songs].index[0]
    distance=sorted(list(enumerate(similar[idx])),reverse=True,key=lambda x:x[1])
    song=[]
    for s_id in distance[1:21]:
        song.append(df.iloc[s_id[0]].song)
    return song

In [53]:
recommend('Bang-A-Boomerang')

['Maybe You Should Know',
 'Our Town',
 "Nothin' But Love",
 'Tell Me',
 'Get Out Of Town',
 "Ain't No Love In The Heart Of The City",
 'Maybe Today',
 "Don't Tell Me You're Not In Love",
 "Why Can't This Be Love",
 'This Town',
 'Clown Town',
 'Got Me Goin',
 "Ain't Got The Time",
 "That's Tough",
 "Tell Me There's A Heaven",
 "Nothin' For Nothin'",
 "It's Not Just Me",
 'My Little Town',
 'Acorns Orioles',
 'Our Town']

In [54]:
import pickle

In [55]:
pickle.dump(similar,open('similar.pkl','wb'))
pickle.dump(df,open('df.pkl','wb'))